FROM node:20-alpine AS build
WORKDIR /app

ENV NPM_CONFIG_LOGLEVEL=info

COPY package*.json ./
RUN npm install --no-audit --no-fund

COPY angular.json tsconfig.json tsconfig.app.json ./
COPY src ./src

RUN npm run build

FROM nginx:1.27-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/sob-controle-web/browser /usr/share/nginx/html

EXPOSE 80